version: '3.9'

services:
  web:
    container_name: django-project-template-web
    build:
      context: .
      dockerfile: Dockerfile.dev
#      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - minio
    volumes:
      - .:/opt/project
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    container_name: django-project-template-db
    image: postgres:15-alpine
    volumes:
      - core_db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 1s
      timeout: 1s
      retries: 10
    ports:
      - "5432:5432"

  minio:
    container_name: django-project-template-minio
    image: bitnami/minio:latest
    volumes:
      - minio_data:/data
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
      - MINIO_DEFAULT_BUCKETS=${AWS_STORAGE_BUCKET_NAME}
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  core_db_data: { }
  minio_data: { }

