# Generated by Django 4.2.2 on 2023-07-27 13:54

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Site Name", max_length=255)),
                ("description", models.TextField(default="Site Description")),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("tag_colors", django_jsonform.models.fields.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
    ]
