# Generated by Django 4.2.4 on 2023-10-10 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_alter_post_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CR", "Created"),
                            ("UP", "Updated"),
                            ("RS", "Reassigned"),
                            ("DS", "Disabled"),
                            ("DL", "Deleted"),
                        ],
                        default="CR",
                        max_length=255,
                        verbose_name="Action",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Audit Trail Description", verbose_name="Description"
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(verbose_name="Target Object ID"),
                ),
                (
                    "from_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="From Object ID"
                    ),
                ),
                (
                    "to_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="To Object ID"
                    ),
                ),
                (
                    "from_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_content_type",
                        to="contenttypes.contenttype",
                        verbose_name="From Content Type",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_content_type",
                        to="contenttypes.contenttype",
                        verbose_name="Target Content Type",
                    ),
                ),
                (
                    "to_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_content_type",
                        to="contenttypes.contenttype",
                        verbose_name="To Content Type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Trail",
                "verbose_name_plural": "Audit Trails",
                "indexes": [
                    models.Index(
                        fields=["target_content_type", "target_object_id"],
                        name="core_auditt_target__bb4aef_idx",
                    ),
                    models.Index(
                        fields=["from_content_type", "from_object_id"],
                        name="core_auditt_from_co_120acf_idx",
                    ),
                    models.Index(
                        fields=["to_content_type", "to_object_id"],
                        name="core_auditt_to_cont_7b1cb8_idx",
                    ),
                ],
            },
        ),
    ]
